### ISSUE TITLE
Base rem-sizing is off for the max size

### ISSUE THREAD

**Issue by tinacious** [johnpolacek/scrolldeck.js#20]
Hi there, when expanding larger than the first specified breakpoint, the font size goes back down to the size before.

Instead of this:

``` css
@media (min-width: 1520px) {
    html {
        font-size: 12px;
    }
}
```

It should be this:

``` css
@media (max-width: 1401px) and (min-width: 1520px) {
    html {
        font-size: 12px;
    }
}
```
